### ISSUE TITLE
Implement search quote feature

### ISSUE THREAD

**Issue by nirajgiriXD** [nirajgiriXD/garden-of-quotes#10]
## Description

There is already  a button available as `Search Quote` but it is not functional. When the button is clicked a search field should appear from which the user should be able to search quotes on the basis of quote phrase, author or tags.

---

## Expectation

Search feature should be implemented.

**Comment by Sandesh-Ghimire** [comment]
i will work on this.

**Comment by nirajgiriXD** [comment]
> i will work on this.

Great! I have assigned you this task 🥳

**Comment by nirajgiriXD** [comment]
@Sandesh-Ghimire, if possible could you help improve the suggestions list design.
