### ISSUE TITLE
Issue with navbar.tsx

### ISSUE THREAD

**Issue by Sandesh-Ghimire** [nirajgiriXD/garden-of-quotes#30]
There is a error in navbar  component. That was requested by @nirajgiriXD to modify in pull request, as suggested i did commit those changes which was changed by @nirajgiriXD 
![Screenshot 2024-01-01 at 10-38-16 Garden of Quotes](https://github.com/nirajgiriXD/garden-of-quotes/assets/62834029/6b779ba0-74ac-4351-b23c-c7b8b0a69aca)

Solve those issues to navbar component.

**Comment by nirajgiriXD** [comment]
Hi @Sandesh-Ghimire,
I have refactored the code and pushed the changes to the main branch. Please pull the latest changes and let me know if there are any issues.
